spring:
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

app:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:900}
    refresh-token-expiration-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION_SECONDS:604800}
