services:
  db:
    image: postgres:17
    container_name: restaurantapi-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    depends_on:
      - db
    image: dbeaver/cloudbeaver:26.1.3
    container_name: restaurantapi-dbeaver
    ports:
      - "8978:8978"
    restart: always
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace

volumes:
  db-data:
  dbeaver-data:
  
